name: Split SRT into Multiple Parts

on:
  workflow_dispatch:
    inputs:
      srt_file:
        description: 'Path to the SRT file'
        required: false
        default: 'HUAWEI.srt'
      parts:
        description: 'How many parts to split into'
        required: false
        default: '2'

jobs:
  split-srt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Split SRT file into parts
        run: |
          set -e
          srt_file="${{ github.event.inputs.srt_file || 'HUAWEI.srt' }}"
          parts="${{ github.event.inputs.parts || 2 }}"

          # 统计总字幕块数
          total_blocks=$(awk '/^[0-9]+$/{n++} END{print n}' "$srt_file")
          if [ "$parts" -lt 1 ]; then
            echo "分割份数最少为1"
            exit 1
          fi
          if [ "$parts" -gt "$total_blocks" ]; then
            echo "分割份数大于总字幕块数，自动调整为$((total_blocks))份"
            parts=$total_blocks
          fi

          # 计算每份大致块数
          blocks_per_part=$((total_blocks / parts))
          remainder=$((total_blocks % parts))

          # 计算每份的起止块号
          declare -a start_blocks
          declare -a end_blocks
          current=1
          for ((i=0;i<parts;i++)); do
            start_blocks[i]=$current
            extra=$(( i < remainder ? 1 : 0 ))
            count=$((blocks_per_part + extra))
            end_blocks[i]=$((current+count-1))
            current=$((current+count))
          done

          # 获取每个分割点的行号
          awk '/^[0-9]+$/{n++; idx[n]=NR} END{for(i=1;i<=n;i++) print idx[i]}' "$srt_file" > block_lines.txt
          mapfile -t block_lines < block_lines.txt
          total_lines=$(wc -l < "$srt_file")

          for ((i=0;i<parts;i++)); do
            part_file="${srt_file%.srt}_part$((i+1)).srt"
            start_idx=$((start_blocks[i]-1))
            end_idx=$((end_blocks[i]-1))
            start_line=${block_lines[$start_idx]}
            if [ "$i" -eq $((parts-1)) ]; then
              # 最后一份，包含到文件结尾
              tail -n +"$start_line" "$srt_file" > "$part_file"
            else
              end_line=$((block_lines[end_idx+1]-1))
              sed -n "${start_line},${end_line}p" "$srt_file" > "$part_file"
            fi
            echo "生成：$part_file （块号：${start_blocks[i]} ~ ${end_blocks[i]}）"
          done

      - name: Upload split SRT files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: split-srt-files
          path: |
            *_part*.srt
