name: YouTube Info
on:
  workflow_dispatch:

jobs:
  list_video_streams:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install/Upgrade yt-dlp using pip
        run: pip install --upgrade --force-reinstall "https://github.com/yt-dlp/yt-dlp/archive/master.tar.gz"

      - name: Verify yt-dlp version
        run: yt-dlp --version
        
      - name: List video streams 
        run: yt-dlp --verbose --cookies cookies.txt --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36" -F "https://youtu.be/0vh_TP8Cl0k?si=yKLG4XSKcfSN4Nd0"
