name: YouTube Info
on:
  workflow_dispatch:

jobs:
  list_video_streams:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install/Upgrade yt-dlp using pip
        run: pip install --upgrade yt-dlp

      - name: Verify yt-dlp version
        run: yt-dlp --version
        
      - name: List video streams 
        run: yt-dlp -F "https://youtu.be/0vh_TP8Cl0k?si=yKLG4XSKcfSN4Nd0"
